/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame
{

    /**
     * Creates new form Login
     */
    public Login ()
    {
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        IniciaS = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        Btn_login = new javax.swing.JLabel();
        lblRecordarClave = new javax.swing.JLabel();
        lblBtnCrearCuenta = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Padlock = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 175, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        Login.setForeground(new java.awt.Color(93, 95, 239));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        jPanel2.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, 50));

        IniciaS.setBackground(new java.awt.Color(0, 0, 0));
        IniciaS.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        IniciaS.setForeground(new java.awt.Color(0, 0, 0));
        IniciaS.setText("Iniciar Sesión");
        jPanel2.add(IniciaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel3.setBackground(new java.awt.Color(236, 236, 236));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Candado.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 50, 50));

        txtUsuario1.setBackground(new java.awt.Color(236, 236, 236));
        txtUsuario1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txtUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario1.setText("Nombre de usuario");
        txtUsuario1.setBorder(null);
        jPanel2.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 300, 50));

        txtContrasena.setBackground(new java.awt.Color(236, 236, 236));
        txtContrasena.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(204, 204, 204));
        txtContrasena.setText("jPasswordField1");
        txtContrasena.setBorder(null);
        txtContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 300, 50));

        Btn_login.setBackground(new java.awt.Color(120, 121, 241));
        Btn_login.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Btn_login.setForeground(new java.awt.Color(255, 255, 255));
        Btn_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn_login.setText("Login");
        Btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_login.setOpaque(true);
        jPanel2.add(Btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 340, 50));

        lblRecordarClave.setBackground(new java.awt.Color(204, 204, 204));
        lblRecordarClave.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblRecordarClave.setForeground(new java.awt.Color(102, 102, 102));
        lblRecordarClave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecordarClave.setText("Recordar Contraseña");
        lblRecordarClave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblRecordarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 150, 20));

        lblBtnCrearCuenta.setBackground(new java.awt.Color(236, 236, 236));
        lblBtnCrearCuenta.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblBtnCrearCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lblBtnCrearCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnCrearCuenta.setText("Crear cuenta");
        lblBtnCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnCrearCuenta.setOpaque(true);
        jPanel2.add(lblBtnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 370, 50));

        User.setBackground(new java.awt.Color(236, 236, 236));
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario.png"))); // NOI18N
        User.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        User.setOpaque(true);
        jPanel2.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, 50));

        Padlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MicrosoftTeams-image.png"))); // NOI18N
        jPanel2.add(Padlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 446, 512));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bk1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bk2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ())
            {
                if ("Nimbus".equals (info.getName ()))
                {
                    javax.swing.UIManager.setLookAndFeel (info.getClassName ());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger (Login.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger (Login.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger (Login.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger (Login.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable ()
        {
            public void run ()
            {
                new Login ().setVisible (true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_login;
    private javax.swing.JLabel IniciaS;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Padlock;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBtnCrearCuenta;
    private javax.swing.JLabel lblRecordarClave;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
